version: "3"

networks:
  stack_ponte:
    external: true

services:
  frontend_albank_prod:
    container_name: "frontend_albank_prod"
    image: "webdevops/apache:latest"
    restart: always
    working_dir: /app
    volumes:
      - ${PATHCLIENTES}/albank/front/dist:/app
    networks:
      - stack_ponte
    ports:
      - "8778:80"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontalbank.rule=Host(`albank.${DOMAIN}`, `oalbank.com.br`,`www.oalbank.com.br`)
      - traefik.http.services.frontalbank.loadbalancer.server.port=80

  golangalbank_prod:
    container_name: "golangalbank_prod"
    restart: always
    image: golang:1.15.7
    volumes:
      - ${PATHCLIENTES}/albank/back:/app
    ports:
      - 3037:8000
    networks:
      - stack_ponte
    command: "/bin/sh -c 'cd /app && ls && ./main'"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.goalbank.rule=Host(`goalbank.${DOMAIN}`)
      - traefik.http.services.goalbank.loadbalancer.server.port=8000
