version: "2"

networks:
  internal:
    driver: bridge

services:
  frontend_allbank:
    container_name: "frontend_allbank"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "../../front:/app"
    command: "yarn dev"
    networks:
      - internal
    ports:
      - "3090:3000"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontallbank.rule=Host(`allbank.localhost`)
      - traefik.http.services.frontallbank.loadbalancer.server.port=3000


